addons:
  apt:
    packages:
      - lynx
language: java
sudo: false
script: mvn clean -Dtest=StudentControllerTest3 test && mvn surefire-report:report
notifications:
    slack: cKd3hI9z4KuWJpvXq6H5DvH7
after_success:
      - if [ -f /home/travis/build/meenaanand/springdata1/app/build/outputs/lint-results-debug.html ]; then lynx -dump /home/travis/build/meenaanand/springdata1/app/build/outputs/lint-results-debug.html; fi
